#
# nmake makefile to build AVB test tools (I219 and I210)
#

!IF "$(CFG)" == ""
CFG=Release
!ENDIF

CC=cl.exe
CFLAGS=/nologo /W3 /EHsc /DWIN32 /D_WINDOWS /DUNICODE /D_UNICODE /std:c++14 /O2
LDFLAGS=/nologo
LIBS=kernel32.lib user32.lib

!IF "$(CFG)" == "Debug"
CFLAGS=$(CFLAGS) /Zi /Od
LDFLAGS=$(LDFLAGS) /DEBUG
!ENDIF

all: avb_test_i219.exe avb_test_i210.exe avb_test_portability.exe avb_test_i217.exe avb_test_i225.exe avb_test_i226_um.exe

avb_test_i219.exe: tests\\device_specific\\i219\\avb_test_i219.c
	$(CC) $(CFLAGS) $** /link $(LDFLAGS) $(LIBS) /out:$@

avb_test_i210.exe: tests\\device_specific\\i210\\avb_test_i210.c
	$(CC) $(CFLAGS) $** /link $(LDFLAGS) $(LIBS) /out:$@

avb_test_portability.exe: tests\\portability\\avb_test_portability.c tests\\common\\avb_test_common.c
	$(CC) $(CFLAGS) /I include /I external\\intel_avb\\lib /I intel-ethernet-regs\\gen $** /link $(LDFLAGS) $(LIBS) /out:$@
avb_test_i217.exe: tests\device_specific\i217\avb_test_i217.c tests\common\avb_test_common.c
	$(CC) $(CFLAGS) /I include /I external\intel_avb\lib /I intel-ethernet-regs\gen $** /link $(LDFLAGS) $(LIBS) /out:$@

avb_test_i225.exe: tests\device_specific\i225\avb_test_i225.c tests\common\avb_test_common.c
	$(CC) $(CFLAGS) /I include /I external\intel_avb\lib /I intel-ethernet-regs\gen $** /link $(LDFLAGS) $(LIBS) /out:$@

avb_test_i226_um.exe: tests\device_specific\i226\avb_test_i226_um.c tests\common\avb_test_common.c
	$(CC) $(CFLAGS) /I include /I external\intel_avb\lib /I intel-ethernet-regs\gen $** /link $(LDFLAGS) $(LIBS) /out:$@
clean:
	del /f /q *.obj *.pdb *.exe 2>NUL
