#Requires -Version 5.1
<#
.SYNOPSIS
    Git pre-commit hook: enforces SSOT and magic number rules.

.DESCRIPTION
    Blocks commits that violate:
      SSOT-001  Duplicate IOCTL definitions outside include/avb_ioctl.h
      SSOT-003  Files not using the SSOT header include path
      SSOT-004  SSOT header missing required IOCTLs
      REGS-002  Raw hex magic-number literals in src/ or devices/

    Triggered only when at least one .c / .h / .cpp file under
    src/, devices/, include/, tests/, or tools/ is staged.

    Tests:
      tests/verification/ssot/Test-SSOT-001-NoDuplicates.ps1
      tests/verification/ssot/Test-SSOT-003-IncludePattern.ps1
      tests/verification/ssot/Test-SSOT-004-Completeness.ps1
      tests/verification/regs/Test-REGS-002-MagicNumberDetection.ps1

.NOTES
    Do NOT edit this file directly to bypass checks.
    Use  git commit --no-verify  only in justified emergencies.
    Install:  powershell -File tools/hooks/Install-Hooks.ps1
#>

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Repo root = 2 dirs up from  tools/hooks/
# ---------------------------------------------------------------------------
$RepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

# ---------------------------------------------------------------------------
# 1. Collect staged file paths (relative to repo root)
# ---------------------------------------------------------------------------
Push-Location $RepoRoot
try {
    $staged = & git diff --cached --name-only --diff-filter=ACMR 2>&1
    $gitExitCode = $LASTEXITCODE
} finally {
    Pop-Location
}

if ($gitExitCode -ne 0 -or -not $staged) {
    exit 0   # Nothing staged or not inside a Git repo
}

# ---------------------------------------------------------------------------
# 2. Decide which suites to run
#    - SSOT checks     : any .c / .h / .cpp under tracked directories
#    - REGS-002 check  : .c / .h under src/ or devices/ only
# ---------------------------------------------------------------------------
$sourcePattern   = '^(src|devices|include|tests|tools)[/\\].*\.(c|h|cpp)$'
$registerPattern = '^(src|devices)[/\\].*\.(c|h)$'

$hasSourceChanges   = $staged | Where-Object { $_ -match $sourcePattern }
$hasRegisterChanges = $staged | Where-Object { $_ -match $registerPattern }

if (-not $hasSourceChanges) {
    # No changes to C/C++ source files - nothing to enforce
    exit 0
}

# ---------------------------------------------------------------------------
# 3. Run checks
# ---------------------------------------------------------------------------
$banner = '-' * 52

Write-Host ""
Write-Host $banner                       -ForegroundColor Cyan
Write-Host '  Pre-commit: SSOT & Magic Number Enforcement'  -ForegroundColor Cyan
Write-Host $banner                       -ForegroundColor Cyan
Write-Host ("  Staged files : {0}" -f $staged.Count) -ForegroundColor Gray
Write-Host  '  Source changes detected - running compliance checks' -ForegroundColor Gray
Write-Host ''

$ssotDir = Join-Path $RepoRoot 'tests\verification\ssot'
$regsDir = Join-Path $RepoRoot 'tests\verification\regs'

$testsRun    = 0
$testsFailed = 0

function Invoke-CheckScript {
    param(
        [string] $Script,
        [string] $Label
    )

    Write-Host "  $([char]0x25B6) $Label" -ForegroundColor Yellow

    if (-not (Test-Path $Script)) {
        Write-Host "    [SKIP] Script not found: $Script" -ForegroundColor DarkYellow
        return
    }

    $exitCode = 0
    try {
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script
        $exitCode = $LASTEXITCODE
    } catch {
        Write-Host "    [ERROR] $_" -ForegroundColor Red
        $exitCode = 1
    }

    $script:testsRun++
    if ($exitCode -eq 0) {
        Write-Host "    [PASSED]" -ForegroundColor Green
    } else {
        $script:testsFailed++
        Write-Host "    [FAILED]" -ForegroundColor Red
    }
    Write-Host ""
}

# -- SSOT suite (runs whenever any source file is staged) --
Invoke-CheckScript `
    -Script (Join-Path $ssotDir 'Test-SSOT-001-NoDuplicates.ps1') `
    -Label  'SSOT-001  No duplicate IOCTL definitions'

Invoke-CheckScript `
    -Script (Join-Path $ssotDir 'Test-SSOT-003-IncludePattern.ps1') `
    -Label  'SSOT-003  SSOT include-path compliance'

Invoke-CheckScript `
    -Script (Join-Path $ssotDir 'Test-SSOT-004-Completeness.ps1') `
    -Label  'SSOT-004  SSOT header completeness'

# -- Magic-number suite (runs only when src/ or devices/ files are staged) --
if ($hasRegisterChanges) {
    Invoke-CheckScript `
        -Script (Join-Path $regsDir 'Test-REGS-002-MagicNumberDetection.ps1') `
        -Label  'REGS-002  No magic-number hex literals'
}

# ---------------------------------------------------------------------------
# 4. Summary & gate
# ---------------------------------------------------------------------------
Write-Host $banner -ForegroundColor Cyan
$allPassed = ($testsFailed -eq 0)
$color     = if ($allPassed) { 'Green' } else { 'Red' }

Write-Host ("  Results: {0}/{1} checks passed" -f ($testsRun - $testsFailed), $testsRun) `
           -ForegroundColor $color
Write-Host $banner -ForegroundColor Cyan

if (-not $allPassed) {
    Write-Host ""
    Write-Host "  *** Commit BLOCKED ***" -ForegroundColor Red
    Write-Host "  Fix the violations reported above, then re-run git commit." -ForegroundColor Red
    Write-Host "  Emergency bypass (logs violation): git commit --no-verify" -ForegroundColor DarkYellow
    Write-Host ""
    exit 1
}

Write-Host ""
Write-Host '  All checks passed - proceeding with commit.' -ForegroundColor Green
Write-Host ""
exit 0
