//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "IntelAvbFilter" event count 4
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = 5dc1ca46-b07f-4a4f-9d02-1a02e7ec24e4
EXTERN_C __declspec(selectany) const GUID INTELAVBFILTER_PROVIDER = {0x5dc1ca46, 0xb07f, 0x4a4f, {0x9d, 0x02, 0x1a, 0x02, 0xe7, 0xec, 0x24, 0xe4}};

#ifndef INTELAVBFILTER_PROVIDER_Traits
#define INTELAVBFILTER_PROVIDER_Traits NULL
#endif // INTELAVBFILTER_PROVIDER_Traits

//
// Channel
//
#define INTELAVBFILTER_PROVIDER_CHANNEL_Sys 0x8
#define INTELAVBFILTER_PROVIDER_CHANNEL_Sys_KEYWORD 0x8000000000000000

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_DRIVER_INIT = {0x1, 0x0, 0x8, 0x4, 0x0, 0x0, 0x8000000000000000};
#define EVT_DRIVER_INIT_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_IOCTL_ERROR = {0x64, 0x0, 0x8, 0x2, 0x0, 0x0, 0x8000000000000000};
#define EVT_IOCTL_ERROR_value 0x64
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PHC_FORCESET_WARN = {0xc8, 0x0, 0x8, 0x3, 0x0, 0x0, 0x8000000000000000};
#define EVT_PHC_FORCESET_WARN_value 0xc8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_HARDWARE_FAULT = {0x12c, 0x0, 0x8, 0x1, 0x0, 0x0, 0x8000000000000000};
#define EVT_HARDWARE_FAULT_value 0x12c

#define MSG_EVT_DRIVER_INIT_message          0x00000001L
#define MSG_EVT_IOCTL_ERROR_message          0x00000064L
#define MSG_EVT_PHC_FORCESET_WARN_message    0x000000C8L
#define MSG_EVT_HARDWARE_FAULT_message       0x0000012CL
